version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamnotification-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
      - ENVIRONMENT=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=streamnotification
      # Add your Twitch, Discord, and Twitter credentials here
      # - TWITCH_CLIENT_ID=your_client_id
      # - TWITCH_CLIENT_SECRET=your_client_secret
      # - DISCORD_BOT_TOKEN=your_discord_bot_token
      # - TWITTER_API_KEY=your_twitter_api_key
      # - TWITTER_API_SECRET=your_twitter_api_secret
      # - TWITTER_ACCESS_TOKEN=your_twitter_access_token
      # - TWITTER_ACCESS_SECRET=your_twitter_access_secret
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: streamnotification-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=streamnotification
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local