version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamnotification-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PORT=8080
      - ENVIRONMENT=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=streamnotification
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: streamnotification-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=streamnotification
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local